-- KLINIKFISIKAPKU MEMBER AREA - SUPABASE SETUP
-- Jalankan seluruh isi file ini sekali di Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.member_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  nama text not null default '',
  wa text not null default '',
  sekolah text not null default '',
  jenjang text not null default '' check (jenjang in ('','sd','smp','sma')),
  paket text not null default '',
  status text not null default 'pending' check (status in ('pending','aktif','ditolak','nonaktif','expired','dihapus')),
  berakhir timestamptz,
  catatan_admin text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.member_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.member_packages (
  id bigint generated by default as identity primary key,
  nama text not null unique,
  durasi_hari integer not null default 30 check (durasi_hari > 0),
  harga bigint not null default 0 check (harga >= 0),
  deskripsi text not null default '',
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.member_content (
  id uuid primary key default gen_random_uuid(),
  jenjang text not null check (jenjang in ('sd','smp','sma')),
  jenis text not null default 'soal',
  tujuan text,
  topik text not null default '',
  judul text not null default '',
  visible boolean not null default true,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.is_member_admin()
returns boolean language sql stable security definer set search_path = ''
as $$ select exists(select 1 from public.member_admins a where a.user_id = auth.uid()); $$;

create or replace function public.handle_new_member()
returns trigger language plpgsql security definer set search_path = ''
as $$
begin
  insert into public.member_profiles(id,email,nama,wa,sekolah,jenjang,paket)
  values(
    new.id, coalesce(new.email,''), coalesce(new.raw_user_meta_data->>'nama',new.raw_user_meta_data->>'full_name',''),
    coalesce(new.raw_user_meta_data->>'wa',''), coalesce(new.raw_user_meta_data->>'sekolah',''),
    coalesce(new.raw_user_meta_data->>'jenjang',''), coalesce(new.raw_user_meta_data->>'paket','')
  ) on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created_member on auth.users;
create trigger on_auth_user_created_member after insert on auth.users
for each row execute function public.handle_new_member();

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists member_profiles_updated_at on public.member_profiles;
create trigger member_profiles_updated_at before update on public.member_profiles for each row execute function public.set_updated_at();
drop trigger if exists member_packages_updated_at on public.member_packages;
create trigger member_packages_updated_at before update on public.member_packages for each row execute function public.set_updated_at();
drop trigger if exists member_content_updated_at on public.member_content;
create trigger member_content_updated_at before update on public.member_content for each row execute function public.set_updated_at();

create or replace function public.complete_member_profile(p_nama text,p_wa text,p_sekolah text,p_jenjang text,p_paket text)
returns void language plpgsql security definer set search_path = ''
as $$
begin
  if auth.uid() is null then raise exception 'Harus login'; end if;
  if p_jenjang not in ('sd','smp','sma') then raise exception 'Jenjang tidak valid'; end if;
  update public.member_profiles set nama=trim(p_nama),wa=trim(p_wa),sekolah=trim(p_sekolah),jenjang=p_jenjang,paket=trim(p_paket)
  where id=auth.uid();
end; $$;

alter table public.member_profiles enable row level security;
alter table public.member_admins enable row level security;
alter table public.member_packages enable row level security;
alter table public.member_content enable row level security;

drop policy if exists "member_read_own_profile" on public.member_profiles;
create policy "member_read_own_profile" on public.member_profiles for select to authenticated using ((select auth.uid())=id or public.is_member_admin());
drop policy if exists "admin_manage_profiles" on public.member_profiles;
create policy "admin_manage_profiles" on public.member_profiles for update to authenticated using (public.is_member_admin()) with check (public.is_member_admin());

drop policy if exists "admin_read_own_role" on public.member_admins;
create policy "admin_read_own_role" on public.member_admins for select to authenticated using ((select auth.uid())=user_id);

drop policy if exists "public_read_active_packages" on public.member_packages;
create policy "public_read_active_packages" on public.member_packages for select to anon,authenticated using (aktif=true or public.is_member_admin());
drop policy if exists "admin_manage_packages" on public.member_packages;
create policy "admin_manage_packages" on public.member_packages for all to authenticated using (public.is_member_admin()) with check (public.is_member_admin());

drop policy if exists "active_member_read_content" on public.member_content;
create policy "active_member_read_content" on public.member_content for select to authenticated using (
  public.is_member_admin() or (visible=true and exists(select 1 from public.member_profiles p where p.id=(select auth.uid()) and p.status='aktif' and (p.berakhir is null or p.berakhir>now())))
);
drop policy if exists "admin_manage_content" on public.member_content;
create policy "admin_manage_content" on public.member_content for all to authenticated using (public.is_member_admin()) with check (public.is_member_admin());

grant usage on schema public to anon,authenticated;
grant select on public.member_packages to anon,authenticated;
grant select on public.member_profiles,public.member_admins,public.member_content to authenticated;
grant insert,update,delete on public.member_packages,public.member_content to authenticated;
grant update on public.member_profiles to authenticated;
grant usage,select on all sequences in schema public to authenticated;
grant execute on function public.is_member_admin() to anon,authenticated;
grant execute on function public.complete_member_profile(text,text,text,text,text) to authenticated;

insert into public.member_packages(nama,durasi_hari,harga,deskripsi) values
('Paket 30 Hari',30,50000,'Akses materi, latihan, dan tryout selama 30 hari.'),
('Paket 90 Hari',90,120000,'Akses materi, latihan, dan tryout selama 90 hari.'),
('Paket 180 Hari',180,200000,'Akses materi, latihan, dan tryout selama 180 hari.'),
('Paket 1 Tahun',365,350000,'Akses materi, latihan, dan tryout selama satu tahun.')
on conflict (nama) do nothing;

-- SETELAH akun admin mendaftar dan memverifikasi email, jalankan perintah berikut
-- dengan mengganti alamat emailnya:
-- insert into public.member_admins(user_id)
-- select id from auth.users where email='EMAIL_ADMIN_ANDA' on conflict do nothing;
