-- KLINIKFISIKAPKU MEMBER AREA - SUPABASE SETUP
-- Jalankan seluruh isi file ini sekali di Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.member_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  nama text not null default '',
  username text not null default '',
  kelas text not null default '',
  wa text not null default '',
  sekolah text not null default '',
  jenjang text not null default '' check (jenjang in ('','sd','smp','sma')),
  paket text not null default '',
  status text not null default 'pending' check (status in ('pending','aktif','ditolak','nonaktif','expired','dihapus')),
  berakhir timestamptz,
  catatan_admin text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Aman dijalankan ulang pada proyek Supabase yang sudah pernah dipasang.
alter table public.member_profiles add column if not exists username text not null default '';
alter table public.member_profiles add column if not exists kelas text not null default '';
create unique index if not exists member_profiles_username_unique
  on public.member_profiles(lower(username)) where username <> '';

create table if not exists public.member_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'super_admin' check (role in ('super_admin','content_admin')),
  display_name text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.member_admins add column if not exists role text not null default 'super_admin';
alter table public.member_admins add column if not exists display_name text not null default '';
alter table public.member_admins add column if not exists active boolean not null default true;
do $$ begin
  if not exists(select 1 from pg_constraint where conname='member_admins_role_check') then
    alter table public.member_admins add constraint member_admins_role_check check(role in ('super_admin','content_admin'));
  end if;
end $$;
create unique index if not exists member_admins_single_super_admin
  on public.member_admins((role)) where role='super_admin';
drop trigger if exists single_member_admin_guard on public.member_admins;
drop function if exists public.enforce_single_member_admin();

create table if not exists public.member_packages (
  id bigint generated by default as identity primary key,
  nama text not null unique,
  durasi_hari integer not null default 30 check (durasi_hari > 0),
  harga bigint not null default 0 check (harga >= 0),
  deskripsi text not null default '',
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.member_content (
  id uuid primary key default gen_random_uuid(),
  jenjang text not null check (jenjang in ('sd','smp','sma')),
  jenis text not null default 'soal',
  tujuan text,
  topik text not null default '',
  judul text not null default '',
  visible boolean not null default true,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.member_content add column if not exists archived_at timestamptz;

create table if not exists public.member_content_versions (
  id bigint generated by default as identity primary key,
  content_id uuid not null,
  version_no integer not null,
  snapshot jsonb not null,
  changed_by uuid references auth.users(id) on delete set null,
  change_reason text not null default '',
  created_at timestamptz not null default now(),
  unique(content_id,version_no)
);

create or replace function public.validate_member_content()
returns trigger language plpgsql set search_path = '' as $$
declare v_status text; v_count int;
begin
  if char_length(trim(new.topik))>160 or char_length(trim(new.judul))>240 then raise exception 'Judul atau topik terlalu panjang'; end if;
  if pg_column_size(new.data)>2500000 then raise exception 'Ukuran konten terlalu besar'; end if;
  if new.jenis not in ('soal','pdf','video','tryout','modul') then raise exception 'Jenis konten tidak valid'; end if;
  v_status:=coalesce(new.data->>'publication_status',case when new.visible then 'published' else 'draft' end);
  if v_status not in ('draft','review','scheduled','published','archived') then raise exception 'Status publikasi tidak valid'; end if;
  if new.jenis='soal' then
    v_count:=coalesce((new.data->>'package_question_count')::int,1);
    if v_count<1 or v_count>100 then raise exception 'Jumlah soal per paket harus 1 sampai 100'; end if;
  end if;
  new.data:=jsonb_set(new.data,'{publication_status}',to_jsonb(v_status),true);
  new.visible:=v_status='published';
  if v_status='archived' then new.archived_at:=coalesce(new.archived_at,now()); else new.archived_at:=null; end if;
  return new;
exception when invalid_text_representation then raise exception 'Jumlah soal tidak valid';
end; $$;
drop trigger if exists validate_member_content_trigger on public.member_content;
create trigger validate_member_content_trigger before insert or update on public.member_content
for each row execute function public.validate_member_content();

create or replace function public.version_member_content()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_next int; v_snapshot jsonb; v_content_id uuid;
begin
  if tg_op='DELETE' then v_snapshot:=to_jsonb(old);v_content_id:=old.id;else v_snapshot:=to_jsonb(new);v_content_id:=new.id;end if;
  select coalesce(max(version_no),0)+1 into v_next from public.member_content_versions
  where content_id=v_content_id;
  insert into public.member_content_versions(content_id,version_no,snapshot,changed_by,change_reason)
  values(v_content_id,v_next,v_snapshot,auth.uid(),case when tg_op='INSERT' then 'dibuat' when tg_op='DELETE' then 'dihapus' else 'diubah' end);
  if tg_op='DELETE' then return old;else return new;end if;
end; $$;
drop trigger if exists version_member_content_trigger on public.member_content;
create trigger version_member_content_trigger after insert or update or delete on public.member_content
for each row execute function public.version_member_content();

-- Progress lintas perangkat, bookmark, hasil tryout, transaksi, dan audit admin.
create table if not exists public.member_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id uuid not null references public.member_content(id) on delete cascade,
  selesai boolean not null default false,
  skor numeric(6,2),
  jawaban jsonb not null default '{}'::jsonb,
  last_opened_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(user_id,content_id)
);

create table if not exists public.member_bookmarks (
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id uuid not null references public.member_content(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,content_id)
);

create table if not exists public.member_tryout_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  paket_tryout text not null default '',
  topik text not null default '',
  benar integer not null default 0 check (benar >= 0),
  jumlah_soal integer not null default 0 check (jumlah_soal >= 0),
  skor numeric(6,2) not null default 0,
  detail jsonb not null default '{}'::jsonb,
  selesai_at timestamptz not null default now()
);

create table if not exists public.member_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  paket text not null,
  jumlah bigint not null check (jumlah >= 0),
  status text not null default 'pending' check (status in ('pending','paid','failed','expired','refunded','cancelled')),
  payment_provider text not null default 'manual',
  payment_id text unique,
  payment_url text,
  paid_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.member_certificates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  judul text not null,
  nomor text not null unique,
  file_url text,
  issued_at timestamptz not null default now()
);

create table if not exists public.member_admin_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  aksi text not null,
  target_type text not null default '',
  target_id text not null default '',
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.member_ai_usage (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  model text not null default '',
  item_count integer not null default 0,
  created_at timestamptz not null default now()
);

create or replace function public.is_member_admin()
returns boolean language sql stable security definer set search_path = ''
as $$ select exists(select 1 from public.member_admins a where a.user_id = auth.uid() and a.active=true); $$;

create or replace function public.is_member_super_admin()
returns boolean language sql stable security definer set search_path = ''
as $$ select exists(select 1 from public.member_admins a where a.user_id=auth.uid() and a.active=true and a.role='super_admin'); $$;

create or replace function public.handle_new_member()
returns trigger language plpgsql security definer set search_path = ''
as $$
begin
  insert into public.member_profiles(id,email,nama,username,kelas,wa,sekolah,jenjang,paket)
  values(
    new.id, coalesce(new.email,''), coalesce(new.raw_user_meta_data->>'nama',new.raw_user_meta_data->>'full_name',''),
    lower(trim(coalesce(new.raw_user_meta_data->>'username',''))), trim(coalesce(new.raw_user_meta_data->>'kelas','')),
    coalesce(new.raw_user_meta_data->>'wa',''), coalesce(new.raw_user_meta_data->>'sekolah',''),
    coalesce(new.raw_user_meta_data->>'jenjang',''), coalesce(new.raw_user_meta_data->>'paket','')
  ) on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created_member on auth.users;
create trigger on_auth_user_created_member after insert on auth.users
for each row execute function public.handle_new_member();

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists member_profiles_updated_at on public.member_profiles;
create trigger member_profiles_updated_at before update on public.member_profiles for each row execute function public.set_updated_at();
drop trigger if exists member_packages_updated_at on public.member_packages;
create trigger member_packages_updated_at before update on public.member_packages for each row execute function public.set_updated_at();
drop trigger if exists member_content_updated_at on public.member_content;
create trigger member_content_updated_at before update on public.member_content for each row execute function public.set_updated_at();
drop trigger if exists member_progress_updated_at on public.member_progress;
create trigger member_progress_updated_at before update on public.member_progress for each row execute function public.set_updated_at();
drop trigger if exists member_orders_updated_at on public.member_orders;
create trigger member_orders_updated_at before update on public.member_orders for each row execute function public.set_updated_at();

create or replace function public.complete_member_profile(p_nama text,p_wa text,p_sekolah text,p_jenjang text,p_paket text)
returns void language plpgsql security definer set search_path = ''
as $$
begin
  if auth.uid() is null then raise exception 'Harus login'; end if;
  if p_jenjang not in ('sd','smp','sma') then raise exception 'Jenjang tidak valid'; end if;
  update public.member_profiles set nama=trim(p_nama),wa=trim(p_wa),sekolah=trim(p_sekolah),jenjang=p_jenjang,paket=trim(p_paket)
  where id=auth.uid();
end; $$;

-- Membuat order dengan harga dari database, bukan dari nilai yang dikirim browser.
-- Edge Function pembayaran dapat memakai id hasil fungsi ini untuk membuat transaksi
-- Midtrans/Xendit, lalu webhook tervalidasi mengubah status menjadi paid.
create or replace function public.create_member_order(p_paket text,p_provider text default 'manual')
returns uuid language plpgsql security definer set search_path = ''
as $$
declare v_id uuid; v_harga bigint;
begin
  if auth.uid() is null then raise exception 'Harus login'; end if;
  select harga into v_harga from public.member_packages where nama=p_paket and aktif=true;
  if v_harga is null then raise exception 'Paket tidak tersedia'; end if;
  insert into public.member_orders(user_id,paket,jumlah,payment_provider)
  values(auth.uid(),p_paket,v_harga,coalesce(nullif(trim(p_provider),''),'manual')) returning id into v_id;
  return v_id;
end; $$;

alter table public.member_profiles enable row level security;
alter table public.member_admins enable row level security;
alter table public.member_packages enable row level security;
alter table public.member_content enable row level security;
alter table public.member_progress enable row level security;
alter table public.member_bookmarks enable row level security;
alter table public.member_tryout_attempts enable row level security;
alter table public.member_orders enable row level security;
alter table public.member_certificates enable row level security;
alter table public.member_admin_logs enable row level security;
alter table public.member_ai_usage enable row level security;
alter table public.member_content_versions enable row level security;

drop policy if exists "member_read_own_profile" on public.member_profiles;
create policy "member_read_own_profile" on public.member_profiles for select to authenticated using ((select auth.uid())=id or public.is_member_super_admin());
drop policy if exists "admin_manage_profiles" on public.member_profiles;
create policy "admin_manage_profiles" on public.member_profiles for update to authenticated using (public.is_member_super_admin()) with check (public.is_member_super_admin());

drop policy if exists "admin_read_own_role" on public.member_admins;
create policy "admin_read_own_role" on public.member_admins for select to authenticated using ((select auth.uid())=user_id);
drop policy if exists "super_admin_manage_roles" on public.member_admins;
create policy "super_admin_manage_roles" on public.member_admins for all to authenticated using(public.is_member_super_admin()) with check(public.is_member_super_admin());

drop policy if exists "public_read_active_packages" on public.member_packages;
create policy "public_read_active_packages" on public.member_packages for select to anon,authenticated using (aktif=true or public.is_member_admin());
drop policy if exists "admin_manage_packages" on public.member_packages;
create policy "admin_manage_packages" on public.member_packages for all to authenticated using (public.is_member_super_admin()) with check (public.is_member_super_admin());

drop policy if exists "active_member_read_content" on public.member_content;
create policy "active_member_read_content" on public.member_content for select to authenticated using (
  public.is_member_admin() or (visible=true and exists(select 1 from public.member_profiles p where p.id=(select auth.uid()) and p.status='aktif' and (p.berakhir is null or p.berakhir>now())))
);
drop policy if exists "admin_manage_content" on public.member_content;
create policy "admin_manage_content" on public.member_content for all to authenticated using (public.is_member_admin()) with check (public.is_member_admin());

drop policy if exists "member_manage_own_progress" on public.member_progress;
create policy "member_manage_own_progress" on public.member_progress for all to authenticated
using ((select auth.uid())=user_id or public.is_member_super_admin())
with check ((select auth.uid())=user_id or public.is_member_super_admin());
drop policy if exists "member_manage_own_bookmarks" on public.member_bookmarks;
create policy "member_manage_own_bookmarks" on public.member_bookmarks for all to authenticated
using ((select auth.uid())=user_id or public.is_member_super_admin())
with check ((select auth.uid())=user_id or public.is_member_super_admin());
drop policy if exists "member_manage_own_attempts" on public.member_tryout_attempts;
create policy "member_manage_own_attempts" on public.member_tryout_attempts for all to authenticated
using ((select auth.uid())=user_id or public.is_member_super_admin())
with check ((select auth.uid())=user_id or public.is_member_super_admin());
drop policy if exists "member_read_own_orders" on public.member_orders;
create policy "member_read_own_orders" on public.member_orders for select to authenticated
using ((select auth.uid())=user_id or public.is_member_super_admin());
drop policy if exists "member_create_own_order" on public.member_orders;
create policy "member_create_own_order" on public.member_orders for insert to authenticated
with check ((select auth.uid())=user_id and status='pending');
drop policy if exists "admin_manage_orders" on public.member_orders;
create policy "admin_manage_orders" on public.member_orders for all to authenticated
using (public.is_member_super_admin()) with check (public.is_member_super_admin());
drop policy if exists "member_read_own_certificates" on public.member_certificates;
create policy "member_read_own_certificates" on public.member_certificates for select to authenticated
using ((select auth.uid())=user_id or public.is_member_super_admin());
drop policy if exists "admin_manage_certificates" on public.member_certificates;
create policy "admin_manage_certificates" on public.member_certificates for all to authenticated
using (public.is_member_super_admin()) with check (public.is_member_super_admin());
drop policy if exists "admin_read_logs" on public.member_admin_logs;
create policy "admin_read_logs" on public.member_admin_logs for select to authenticated using (public.is_member_super_admin() or admin_id=auth.uid());
drop policy if exists "admin_insert_logs" on public.member_admin_logs;
create policy "admin_insert_logs" on public.member_admin_logs for insert to authenticated with check (public.is_member_admin());
drop policy if exists "admin_read_ai_usage" on public.member_ai_usage;
create policy "admin_read_ai_usage" on public.member_ai_usage for select to authenticated using (public.is_member_admin());
drop policy if exists "admin_read_content_versions" on public.member_content_versions;
create policy "admin_read_content_versions" on public.member_content_versions for select to authenticated using (public.is_member_admin());

grant usage on schema public to anon,authenticated;
grant select on public.member_packages to anon,authenticated;
grant select on public.member_profiles,public.member_admins,public.member_content to authenticated;
grant select,insert,update,delete on public.member_progress,public.member_bookmarks,public.member_tryout_attempts to authenticated;
grant select,insert,update on public.member_orders to authenticated;
grant select,insert,update,delete on public.member_certificates,public.member_admin_logs to authenticated;
grant select on public.member_ai_usage to authenticated;
grant select on public.member_content_versions to authenticated;
grant insert,update,delete on public.member_packages,public.member_content to authenticated;
grant update on public.member_profiles to authenticated;
grant usage,select on all sequences in schema public to authenticated;
grant execute on function public.is_member_admin() to anon,authenticated;
grant execute on function public.is_member_super_admin() to anon,authenticated;
grant execute on function public.complete_member_profile(text,text,text,text,text) to authenticated;
grant execute on function public.create_member_order(text,text) to authenticated;

insert into public.member_packages(nama,durasi_hari,harga,deskripsi) values
('Paket 30 Hari',30,50000,'Akses materi, latihan, dan tryout selama 30 hari.'),
('Paket 90 Hari',90,120000,'Akses materi, latihan, dan tryout selama 90 hari.'),
('Paket 180 Hari',180,200000,'Akses materi, latihan, dan tryout selama 180 hari.'),
('Paket 1 Tahun',365,350000,'Akses materi, latihan, dan tryout selama satu tahun.')
on conflict (nama) do nothing;

-- ============================================================================
-- SECURITY HARDENING v4
-- Bagian ini sengaja berada di akhir agar aman saat seluruh file dijalankan
-- ulang pada instalasi lama. Frontend hanya memakai fungsi-fungsi tervalidasi
-- untuk data sensitif (jawaban, perubahan transaksi, dan log admin).
-- ============================================================================

create table if not exists public.member_answer_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id uuid not null references public.member_content(id) on delete cascade,
  benar boolean,
  created_at timestamptz not null default now()
);

create table if not exists public.member_webhook_events (
  id text primary key,
  provider text not null check (provider in ('midtrans','xendit')),
  order_id uuid references public.member_orders(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.member_answer_attempts enable row level security;
alter table public.member_webhook_events enable row level security;

alter table public.member_profiles drop constraint if exists member_profiles_length_chk;
alter table public.member_profiles add constraint member_profiles_length_chk check (
  char_length(email) <= 254 and char_length(nama) <= 100 and char_length(wa) <= 25
  and char_length(username) <= 30 and char_length(kelas) <= 2
  and char_length(sekolah) <= 150 and char_length(paket) <= 80
  and char_length(catatan_admin) <= 1000
) not valid;

alter table public.member_content drop constraint if exists member_content_size_chk;
alter table public.member_content add constraint member_content_size_chk check (
  char_length(topik) <= 160 and char_length(judul) <= 250
  and pg_column_size(data) <= 5242880
) not valid;

create index if not exists member_answer_attempts_rate_idx
  on public.member_answer_attempts(user_id,content_id,created_at desc);
create index if not exists member_orders_user_created_idx
  on public.member_orders(user_id,created_at desc);

create or replace function public.handle_new_member()
returns trigger language plpgsql security definer set search_path = ''
as $$
declare v_jenjang text; v_username text; v_kelas text;
begin
  if lower(coalesce(new.email,'')) !~ '^[^@]+@gmail\.com$' then raise exception 'Gunakan email Google (@gmail.com)'; end if;
  v_jenjang := lower(coalesce(new.raw_user_meta_data->>'jenjang',''));
  if v_jenjang not in ('','sd','smp','sma') then v_jenjang := ''; end if;
  v_username := lower(trim(coalesce(new.raw_user_meta_data->>'username','')));
  v_kelas := trim(coalesce(new.raw_user_meta_data->>'kelas',''));
  if v_username !~ '^[a-z0-9._]{4,30}$' then raise exception 'Username tidak valid'; end if;
  if v_kelas !~ '^(1|2|3|4|5|6|7|8|9|10|11|12)$' then raise exception 'Kelas tidak valid'; end if;
  insert into public.member_profiles(id,email,nama,username,kelas,wa,sekolah,jenjang,paket)
  values(
    new.id, left(coalesce(new.email,''),254),
    left(trim(coalesce(new.raw_user_meta_data->>'nama',new.raw_user_meta_data->>'full_name','')),100),
    v_username,v_kelas,
    left(trim(coalesce(new.raw_user_meta_data->>'wa','')),25),
    left(trim(coalesce(new.raw_user_meta_data->>'sekolah','')),150),
    v_jenjang,
    left(trim(coalesce(new.raw_user_meta_data->>'paket','')),80)
  ) on conflict (id) do nothing;
  return new;
end; $$;

create or replace function public.choose_member_package(p_package text)
returns void language plpgsql security definer set search_path = ''
as $$
begin
  if auth.uid() is null then raise exception 'Harus login'; end if;
  if not exists(select 1 from public.member_packages where nama=trim(p_package) and aktif=true and nama<>'__PENGATURAN_PEMBAYARAN__') then
    raise exception 'Paket tidak tersedia';
  end if;
  update public.member_profiles set paket=trim(p_package)
  where id=auth.uid() and status<>'aktif';
  if not found then raise exception 'Paket akun aktif hanya dapat diubah oleh admin'; end if;
end; $$;

create or replace function public.complete_member_profile(
  p_nama text,p_wa text,p_sekolah text,p_jenjang text,p_paket text
)
returns void language plpgsql security definer set search_path = ''
as $$
declare v_status text;
begin
  if auth.uid() is null then raise exception 'Harus login'; end if;
  select status into v_status from public.member_profiles where id=auth.uid();
  if v_status is null then raise exception 'Profil tidak ditemukan'; end if;
  if v_status <> 'pending' then raise exception 'Profil hanya dapat dilengkapi saat masih pending'; end if;
  if coalesce(p_jenjang,'') not in ('sd','smp','sma') then raise exception 'Jenjang tidak valid'; end if;
  if char_length(trim(coalesce(p_nama,''))) < 2 or char_length(p_nama) > 100 then raise exception 'Nama tidak valid'; end if;
  if trim(coalesce(p_wa,'')) !~ '^\+?[0-9][0-9 \-]{6,20}$' then raise exception 'Nomor WhatsApp tidak valid'; end if;
  if char_length(coalesce(p_sekolah,'')) > 150 then raise exception 'Nama sekolah terlalu panjang'; end if;
  if not exists(select 1 from public.member_packages where nama=trim(p_paket) and aktif=true) then raise exception 'Paket tidak valid'; end if;
  update public.member_profiles set nama=trim(p_nama),wa=trim(p_wa),sekolah=trim(p_sekolah),jenjang=p_jenjang,paket=trim(p_paket)
  where id=auth.uid();
end; $$;

create or replace function public.member_active_grade()
returns text language sql stable security definer set search_path = ''
as $$
  select p.jenjang from public.member_profiles p
  where p.id=auth.uid() and p.status='aktif' and (p.berakhir is null or p.berakhir>now());
$$;

-- Materi soal dikirim tanpa kunci, pembahasan, video pembahasan, dan kunci
-- yang bersarang pada pernyataan kategori.
create or replace function public.member_secure_content()
returns jsonb language plpgsql stable security definer set search_path = ''
as $$
declare v_grade text; v_package text; v_result jsonb;
begin
  v_grade := public.member_active_grade();
  if coalesce(v_grade,'')='' then raise exception 'Akses member tidak aktif'; end if;
  select p.paket into v_package from public.member_profiles p where p.id=auth.uid();
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',c.id,'jenjang',c.jenjang,'jenis',c.jenis,'tujuan',c.tujuan,
    'topik',c.topik,'judul',c.judul,'visible',c.visible,'created_at',c.created_at,
    'data',case when c.jenis='soal' then
      (c.data - 'kunci' - 'pembahasan' - 'youtube' - 'rubrik') ||
      case when jsonb_typeof(c.data->'statements')='array' then jsonb_build_object(
        'statements',coalesce((select jsonb_agg(jsonb_build_object('text',s.value->>'text') order by s.ord)
          from jsonb_array_elements(c.data->'statements') with ordinality s(value,ord)),'[]'::jsonb)
      ) else '{}'::jsonb end
    else (c.data - 'youtube' - 'source_private') end
  ) order by c.created_at),'[]'::jsonb) into v_result
  from public.member_content c where c.jenjang=v_grade and c.visible=true
    and (not (c.data ? 'packages') or jsonb_typeof(c.data->'packages')<>'array'
      or jsonb_array_length(c.data->'packages')=0 or c.data->'packages' ? coalesce(v_package,''));
  return v_result;
end; $$;

create or replace function public.touch_member_content(p_content_id uuid)
returns void language plpgsql security definer set search_path = ''
as $$
declare v_grade text; v_package text;
begin
  v_grade:=public.member_active_grade();
  if v_grade is null then raise exception 'Akses member tidak aktif'; end if;
  select p.paket into v_package from public.member_profiles p where p.id=auth.uid();
  if not exists(select 1 from public.member_content c where id=p_content_id and jenjang=v_grade and visible=true
    and (not (c.data ? 'packages') or jsonb_typeof(c.data->'packages')<>'array' or jsonb_array_length(c.data->'packages')=0 or c.data->'packages' ? coalesce(v_package,''))) then raise exception 'Konten tidak tersedia'; end if;
  insert into public.member_progress(user_id,content_id,last_opened_at)
  values(auth.uid(),p_content_id,now())
  on conflict(user_id,content_id) do update set last_opened_at=now(),updated_at=now();
end; $$;

create or replace function public.check_member_answer(p_content_id uuid,p_answer jsonb)
returns jsonb language plpgsql security definer set search_path = ''
as $$
declare
  v_grade text; v_package text; v_content public.member_content; v_type text; v_correct boolean;
  v_given text; v_key text; v_given_arr text[]; v_key_arr text[];
  v_attempt_count integer; v_reveal boolean;
begin
  v_grade:=public.member_active_grade();
  if v_grade is null then raise exception 'Akses member tidak aktif'; end if;
  select p.paket into v_package from public.member_profiles p where p.id=auth.uid();
  select * into v_content from public.member_content
  where id=p_content_id and jenjang=v_grade and visible=true and jenis='soal'
    and (not (data ? 'packages') or jsonb_typeof(data->'packages')<>'array' or jsonb_array_length(data->'packages')=0 or data->'packages' ? coalesce(v_package,''));
  if not found then raise exception 'Soal tidak ditemukan'; end if;
  select count(*) into v_attempt_count from public.member_answer_attempts
    where user_id=auth.uid() and content_id=p_content_id and created_at>now()-interval '1 hour';
  if v_attempt_count >= (case when v_content.tujuan='tryout' then 3 else 30 end) then
    raise exception 'Batas percobaan tercapai. Coba lagi satu jam lagi.';
  end if;
  if pg_column_size(coalesce(p_answer,'null'::jsonb))>10000 then raise exception 'Jawaban terlalu besar'; end if;
  v_type:=coalesce(v_content.data->>'tipe','pg4');
  if v_type in ('pg4','pg5') then
    v_given:=trim(coalesce(p_answer#>>'{}','')); v_key:=trim(coalesce(v_content.data->>'kunci',''));
    v_correct:=v_given~'^[0-9]+$' and v_key~'^[0-9]+$' and v_given::int=v_key::int;
  elsif v_type='mcma' then
    select array_agg(value order by value) into v_given_arr from jsonb_array_elements_text(coalesce(p_answer,'[]'::jsonb));
    select array_agg(value order by value) into v_key_arr from jsonb_array_elements_text(coalesce(v_content.data->'kunci','[]'::jsonb));
    v_correct:=coalesce(v_given_arr,'{}')=coalesce(v_key_arr,'{}');
  elsif v_type='kategori' then
    select array_agg(lower(trim(value)) order by ord) into v_given_arr
      from jsonb_array_elements_text(coalesce(p_answer,'[]'::jsonb)) with ordinality a(value,ord);
    select array_agg(lower(trim(value->>'key')) order by ord) into v_key_arr
      from jsonb_array_elements(coalesce(v_content.data->'statements','[]'::jsonb)) with ordinality a(value,ord);
    v_correct:=coalesce(v_given_arr,'{}')=coalesce(v_key_arr,'{}') and cardinality(coalesce(v_key_arr,'{}'))>0;
  elsif v_type='isian' then
    v_correct:=lower(trim(coalesce(p_answer#>>'{}','')))=lower(trim(coalesce(v_content.data->>'kunci','')));
  else
    v_correct:=null;
  end if;
  insert into public.member_answer_attempts(user_id,content_id,benar) values(auth.uid(),p_content_id,v_correct);
  if v_correct is true then
    insert into public.member_progress(user_id,content_id,selesai,skor,jawaban,last_opened_at,completed_at)
    values(auth.uid(),p_content_id,true,100,jsonb_build_object('jawaban',p_answer),now(),now())
    on conflict(user_id,content_id) do update set selesai=true,skor=100,jawaban=excluded.jawaban,last_opened_at=now(),completed_at=coalesce(public.member_progress.completed_at,now()),updated_at=now();
  end if;
  v_reveal:=coalesce(v_content.tujuan,'latihan')<>'tryout' or v_correct is true or v_attempt_count>=2;
  return jsonb_build_object('benar',v_correct,
    'kunci',case when v_reveal then v_content.data->'kunci' else null end,
    'pembahasan',case when v_reveal then coalesce(v_content.data->>'pembahasan','') else '' end,
    'youtube',case when v_reveal then coalesce(v_content.data->>'youtube','') else '' end,
    'review_locked',not v_reveal);
end; $$;

create or replace function public.admin_list_members()
returns setof public.member_profiles language plpgsql stable security definer set search_path = ''
as $$ begin
  if not public.is_member_super_admin() then raise exception 'Hanya Admin Utama'; end if;
  return query select * from public.member_profiles where status<>'dihapus' order by created_at desc;
end; $$;

create or replace function public.admin_list_members_masked()
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare v_result jsonb;
begin
  if not public.is_member_super_admin() then raise exception 'Hanya Admin Utama'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',p.id,'email',case when position('@' in p.email)>1 then left(p.email,3)||'***@'||split_part(p.email,'@',2) else '***' end,
    'nama',p.nama,'username',p.username,'kelas',p.kelas,
    'wa',case when length(regexp_replace(p.wa,'[^0-9]','','g'))>7 then left(regexp_replace(p.wa,'[^0-9]','','g'),4)||'****'||right(regexp_replace(p.wa,'[^0-9]','','g'),4) else '****' end,
    'sekolah',p.sekolah,'jenjang',p.jenjang,'paket',p.paket,'status',p.status,
    'berakhir',p.berakhir,'catatan_admin',p.catatan_admin,'created_at',p.created_at,'updated_at',p.updated_at
  ) order by p.created_at desc),'[]'::jsonb) into v_result
  from public.member_profiles p where p.status<>'dihapus'
    and not exists(select 1 from public.member_admins a where a.user_id=p.id);
  return v_result;
end; $$;

create or replace function public.log_admin_event(p_action text,p_target_type text,p_target_id text,p_detail jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path = ''
as $$ begin
  if not public.is_member_admin() then raise exception 'Hanya admin'; end if;
  if char_length(coalesce(p_action,''))>100 or char_length(coalesce(p_target_type,''))>80 or char_length(coalesce(p_target_id,''))>200 or pg_column_size(coalesce(p_detail,'{}'))>50000 then raise exception 'Log tidak valid'; end if;
  insert into public.member_admin_logs(admin_id,aksi,target_type,target_id,detail)
  values(auth.uid(),p_action,p_target_type,p_target_id,coalesce(p_detail,'{}'));
end; $$;

create or replace function public.admin_update_order(p_id uuid,p_status text)
returns void language plpgsql security definer set search_path = ''
as $$
declare v_order public.member_orders; v_days int; v_base timestamptz;
begin
  if not public.is_member_super_admin() then raise exception 'Hanya Admin Utama'; end if;
  if p_status not in ('pending','paid','failed','expired','refunded','cancelled') then raise exception 'Status tidak valid'; end if;
  select * into v_order from public.member_orders where id=p_id for update;
  if not found then raise exception 'Order tidak ditemukan'; end if;
  if v_order.status='refunded' then raise exception 'Order refund tidak dapat diubah'; end if;
  if v_order.status='paid' and p_status not in ('paid','refunded') then raise exception 'Order dibayar hanya dapat di-refund'; end if;
  update public.member_orders set status=p_status,paid_at=case when p_status='paid' then coalesce(paid_at,now()) else paid_at end where id=p_id;
  if p_status='paid' and v_order.status<>'paid' then
    select durasi_hari into v_days from public.member_packages where nama=v_order.paket;
    select case when status='aktif' and berakhir>now() then berakhir else now() end into v_base from public.member_profiles where id=v_order.user_id for update;
    update public.member_profiles set status='aktif',paket=v_order.paket,berakhir=v_base+make_interval(days=>coalesce(v_days,30)) where id=v_order.user_id;
  end if;
  insert into public.member_admin_logs(admin_id,aksi,target_type,target_id,detail)
  values(auth.uid(),'ubah_status_transaksi','order',p_id::text,jsonb_build_object('dari',v_order.status,'ke',p_status));
end; $$;

create or replace function public.admin_update_member(p_id uuid,p_action text,p_package text default '',p_note text default '')
returns void language plpgsql security definer set search_path = ''
as $$
declare v_profile public.member_profiles; v_days int; v_base timestamptz;
begin
  if not public.is_member_super_admin() then raise exception 'Hanya Admin Utama'; end if;
  if p_action not in ('activate','reject','reactivate','deactivate','soft_delete') then raise exception 'Aksi tidak valid'; end if;
  select * into v_profile from public.member_profiles where id=p_id for update;
  if not found then raise exception 'Member tidak ditemukan'; end if;
  if p_action='activate' then
    select durasi_hari into v_days from public.member_packages where nama=trim(p_package) and aktif=true;
    if v_days is null then raise exception 'Paket tidak valid'; end if;
    v_base:=case when v_profile.status='aktif' and v_profile.berakhir>now() then v_profile.berakhir else now() end;
    update public.member_profiles set status='aktif',paket=trim(p_package),berakhir=v_base+make_interval(days=>v_days),catatan_admin=left(trim(coalesce(p_note,'')),1000) where id=p_id;
  elsif p_action='reject' then
    update public.member_profiles set status='ditolak',catatan_admin=left(trim(coalesce(p_note,'')),1000) where id=p_id;
  elsif p_action='reactivate' then
    select durasi_hari into v_days from public.member_packages where nama=v_profile.paket;
    update public.member_profiles set status='aktif',berakhir=case when v_profile.berakhir>now() then v_profile.berakhir else now()+make_interval(days=>coalesce(v_days,30)) end where id=p_id;
  elsif p_action='deactivate' then
    update public.member_profiles set status='nonaktif',catatan_admin=left(trim(coalesce(p_note,'')),1000) where id=p_id;
  else
    update public.member_profiles set status='dihapus',catatan_admin=left(trim(coalesce(p_note,'')),1000) where id=p_id;
  end if;
  insert into public.member_admin_logs(admin_id,aksi,target_type,target_id,detail)
  values(auth.uid(),'member_'||p_action,'member',p_id::text,jsonb_build_object('paket',p_package,'status_sebelum',v_profile.status,'alasan',left(trim(coalesce(p_note,'')),1000)));
end; $$;

create or replace function public.process_payment_webhook(
  p_event_id text,p_order_id uuid,p_provider text,p_payment_id text,
  p_amount bigint,p_status text,p_payload jsonb
)
returns text language plpgsql security definer set search_path = ''
as $$
declare v_order public.member_orders; v_days int; v_base timestamptz;
begin
  if p_provider not in ('midtrans','xendit') or p_status not in ('pending','paid','failed','expired','refunded') then raise exception 'Payload pembayaran tidak valid'; end if;
  if char_length(coalesce(p_event_id,''))<3 or char_length(p_event_id)>200 then raise exception 'Event ID tidak valid'; end if;
  if exists(select 1 from public.member_webhook_events where id=p_provider||':'||p_event_id) then return 'duplicate'; end if;
  select * into v_order from public.member_orders where id=p_order_id for update;
  if not found then raise exception 'Order tidak ditemukan'; end if;
  if v_order.payment_provider<>p_provider or v_order.jumlah<>p_amount then raise exception 'Provider atau nominal tidak cocok'; end if;
  if v_order.payment_id is not null and p_payment_id<>'' and v_order.payment_id<>p_payment_id then raise exception 'Payment ID tidak cocok'; end if;
  insert into public.member_webhook_events(id,provider,order_id,payload) values(p_provider||':'||p_event_id,p_provider,p_order_id,coalesce(p_payload,'{}'));
  if v_order.status in ('refunded','cancelled') then return 'ignored'; end if;
  if v_order.status='paid' and p_status<>'refunded' then return 'already_paid'; end if;
  update public.member_orders set status=p_status,paid_at=case when p_status='paid' then now() else paid_at end,
    payment_id=coalesce(nullif(p_payment_id,''),payment_id),metadata=coalesce(p_payload,'{}') where id=p_order_id;
  if p_status='paid' then
    select durasi_hari into v_days from public.member_packages where nama=v_order.paket;
    select case when status='aktif' and berakhir>now() then berakhir else now() end into v_base from public.member_profiles where id=v_order.user_id for update;
    update public.member_profiles set status='aktif',paket=v_order.paket,berakhir=v_base+make_interval(days=>coalesce(v_days,30)) where id=v_order.user_id;
  end if;
  return 'processed';
end; $$;

create or replace function public.create_member_order(p_paket text,p_provider text default 'manual')
returns uuid language plpgsql security definer set search_path = ''
as $$
declare v_id uuid; v_price bigint; v_provider text;
begin
  if auth.uid() is null then raise exception 'Harus login'; end if;
  v_provider:=lower(trim(coalesce(p_provider,'manual')));
  if v_provider not in ('manual','midtrans','xendit') then raise exception 'Provider tidak valid'; end if;
  if (select count(*) from public.member_orders where user_id=auth.uid() and created_at>now()-interval '1 day')>=5 then raise exception 'Batas lima pesanan per hari tercapai'; end if;
  select harga into v_price from public.member_packages where nama=trim(p_paket) and aktif=true;
  if v_price is null then raise exception 'Paket tidak tersedia'; end if;
  select id into v_id from public.member_orders where user_id=auth.uid() and paket=trim(p_paket) and payment_provider=v_provider and status='pending' order by created_at desc limit 1;
  if v_id is not null then return v_id; end if;
  insert into public.member_orders(user_id,paket,jumlah,status,payment_provider)
  values(auth.uid(),trim(p_paket),v_price,'pending',v_provider) returning id into v_id;
  return v_id;
end; $$;

-- Kebijakan akhir: peserta tidak pernah membaca tabel konten mentah karena tabel
-- tersebut berisi kunci. Admin tetap dapat mengelolanya melalui RLS.
drop policy if exists "active_member_read_content" on public.member_content;
drop policy if exists "admin_manage_content" on public.member_content;
create policy "admin_manage_content" on public.member_content for all to authenticated
  using(public.is_member_admin()) with check(public.is_member_admin());

drop policy if exists "member_create_own_order" on public.member_orders;
drop policy if exists "admin_manage_orders" on public.member_orders;
create policy "admin_manage_orders" on public.member_orders for select to authenticated using(public.is_member_super_admin());

drop policy if exists "admin_insert_logs" on public.member_admin_logs;

revoke all on public.member_answer_attempts,public.member_webhook_events from anon,authenticated;
revoke insert,update,delete on public.member_orders from authenticated;
revoke insert,update,delete on public.member_progress,public.member_tryout_attempts from authenticated;
revoke insert,update,delete on public.member_admin_logs from authenticated;
revoke update on public.member_profiles from authenticated;
revoke select on public.member_profiles from authenticated;
grant select(id,email,nama,username,kelas,wa,sekolah,jenjang,paket,status,berakhir,created_at,updated_at) on public.member_profiles to authenticated;
grant select on public.member_orders to authenticated;
grant select on public.member_progress,public.member_tryout_attempts to authenticated;

revoke all on function public.handle_new_member() from public,anon,authenticated;
revoke all on function public.member_active_grade() from public,anon;
revoke all on function public.member_secure_content() from public,anon;
revoke all on function public.touch_member_content(uuid) from public,anon;
revoke all on function public.check_member_answer(uuid,jsonb) from public,anon;
revoke all on function public.admin_list_members() from public,anon,authenticated;
revoke all on function public.admin_list_members_masked() from public,anon;
revoke all on function public.log_admin_event(text,text,text,jsonb) from public,anon;
revoke all on function public.admin_update_order(uuid,text) from public,anon;
revoke all on function public.admin_update_member(uuid,text,text,text) from public,anon;
revoke all on function public.process_payment_webhook(text,uuid,text,text,bigint,text,jsonb) from public,anon,authenticated;
revoke all on function public.create_member_order(text,text) from public,anon;
revoke all on function public.choose_member_package(text) from public,anon;
grant execute on function public.choose_member_package(text) to authenticated;
grant execute on function public.member_secure_content() to authenticated;
grant execute on function public.touch_member_content(uuid) to authenticated;
grant execute on function public.check_member_answer(uuid,jsonb) to authenticated;
grant execute on function public.admin_list_members_masked() to authenticated;
grant execute on function public.log_admin_event(text,text,text,jsonb) to authenticated;
grant execute on function public.admin_update_order(uuid,text) to authenticated;
grant execute on function public.admin_update_member(uuid,text,text,text) to authenticated;
grant execute on function public.process_payment_webhook(text,uuid,text,text,bigint,text,jsonb) to service_role;
grant execute on function public.create_member_order(text,text) to authenticated;

-- SETELAH akun Admin Utama mendaftar dan memverifikasi email, jalankan perintah berikut
-- dengan mengganti alamat emailnya:
-- insert into public.member_admins(user_id,role,display_name,active)
-- select id,'super_admin','Admin Utama',true from auth.users
-- where email='EMAIL_ADMIN_ANDA' on conflict do nothing;
